export const COPY = {
  login: {
    title: "登录 · 面镜 Mirror",
    brand: "面镜 Mirror",
    tagline: "照镜子式演练：面试是自我认知的镜子。",
    coverLabel: "考官评分簿 · 第 001 册",
    coverUsageLabel: "演练",
    coverUsageValue: "结构陪练 · 考官追问",
    coverScoringLabel: "批改",
    coverScoringValue: "四维评分 · 逐题批注",
    formTitle: "登录",
    formHint: "邮箱登录，无需密码。",
    emailLabel: "邮箱",
    emailPlaceholder: "输入邮箱",
    magicLink: "发送登录链接",
    github: "使用 GitHub 登录",
    sent: "登录链接已发送，请查收邮箱。",
    emailError: "这行字有问题，换一个邮箱试试。",
    authError: "登录没有完成，请回卷重试。",
  },
  dashboard: {
    title: "面试目录 · 面镜 Mirror",
    brand: "面镜 Mirror",
    navResumes: "简历档案库",
    navNewInterview: "新建面试",
    navSignOut: "退出登录",
    signingOut: "合卷中…",
    headerLabel: "考官评分簿 · 目录",
    headerTitle: "面试目录",
    headerHint:
      "每场面试一行目录条目：编号、岗位、题型、日期、状态章、总分章。未阅卷的卷点开续答，阅卷完成的卷点开看批注。",
    colNo: "编号",
    colPosition: "岗位",
    colType: "题型",
    colDate: "日期",
    colStatus: "状态",
    colScore: "总分",
    statusReady: "待开始",
    statusInProgress: "进行中",
    statusCompleted: "已完成",
    statusGenerating: "出卷中",
    statusDraft: "出卷失败",
    statusAbandoned: "缺考",
    emptyTitle: "尚未开卷",
    emptyHint: "评分簿还是空白册。登记第一场模拟面试，考官依你的简历出题批改。",
    emptyButton: "创建第一场模拟面试",
    loadFailed: "目录没有取回，请刷新本页。",
  },
  resumes: {
    title: "简历 · 面镜 Mirror",
    headerLabel: "卷宗索引 · 简历档案库",
    headerTitle: "简历档案库",
    headerHint: "一卷一卡：每份简历是一张实体档案卡，供各场面试调阅。",
    newArchiveEyebrow: "考官誊录处",
    newArchiveTitle: "新建档案",
    newArchiveHint: "上传 PDF 由考官誊录，或直接粘贴文本入卷。",
    uploadLabel: "上传 PDF 文件",
    uploadHint: "仅收 PDF 原件；扫描件无法誊录。",
    uploadButton: "誊录入卷",
    uploading: "誊录中…",
    pasteLabel: "粘贴简历文本",
    pasteHint: "手边没有 PDF？粘贴全文，效力等同原件入卷。",
    pastePlaceholder: "在此粘贴简历全文……",
    pasteButton: "存为档案",
    saving: "入卷中…",
    listTitle: "档案索引",
    listHint: "按归档时间排序，新档在后。",
    listEmptyTitle: "尚未建档",
    listEmptyHint: "上传第一份简历，面试开卷有据。",
    archiveNoPrefix: "档案",
    dateLabel: "归档日期",
    profileLabel: "画像摘要",
    profileExpand: "展开画像",
    profileCollapse: "收起画像",
    profilePending: "画像待生成：此档案将在首场面试时完成结构化。",
    deleteButton: "销档",
    deleting: "销档中…",
    deleteConfirm: "确认销档？此档案的面试记录将一并销毁。",
    successNote: "已入卷。",
    pasteTooShort: "文本太短：不足 50 字，请粘贴完整简历。",
    notPdf: "仅收 PDF 原件：这份文件不是 PDF，换一份试试。",
    scanned: "誊录失败：这份 PDF 的文本太少，可能是扫描件，请用文字版 PDF。",
    uploadFailed: "誊录没有完成，请重试一次。",
    pasteFailed: "没有存进去，请重试一次。",
    deleteFailed: "销档没有完成，请重试一次。",
    loadFailed: "档案索引没有取回，请刷新本页。",
    loading: "取卷中…",
  },
  interviewNew: {
    title: "新建面试 · 面镜 Mirror",
    headerLabel: "考前登记表 · 开卷登记",
    headerTitle: "新建面试",
    headerHint:
      "三步登记：调卷、报岗、定题。登记完毕，考官依卷出题，约需 10-30 秒。",
    stepOneLabel: "第一步 · 调卷",
    stepOneTitle: "选择简历档案",
    stepOneHint: "从档案库调出一份简历，考官将依此卷出题。",
    resumeEmptyTitle: "尚未建档",
    resumeEmptyHint: "先去简历档案库入卷一份简历，再回来登记面试。",
    resumeEmptyLink: "前往简历档案库",
    loadFailed: "档案索引没有取回，请刷新本页。",
    loading: "取卷中…",
    stepTwoLabel: "第二步 · 报岗",
    stepTwoTitle: "岗位与 JD",
    positionLabel: "目标岗位",
    positionPlaceholder: "如：后端开发工程师",
    jdLabel: "职位描述 JD（可选）",
    jdHint: "粘贴 JD 原文，考官将照此出题；不贴则按岗位常识。",
    jdPlaceholder: "在此粘贴 JD 全文……",
    stepThreeLabel: "第三步 · 定题",
    stepThreeTitle: "题型与题量",
    typeLabel: "题型",
    typeSkill: "技能",
    typeProject: "项目",
    typeBehavioral: "行为",
    typeMixed: "混合",
    typeMixedHint: "技能、项目、行为题搭配",
    countLabel: "题量",
    countHint: "3-10 题，默认 6 题。",
    countDecrease: "减一题",
    countIncrease: "加一题",
    submitButton: "登记完毕 · 开始出卷",
    printingTitle: "考官正在出卷",
    printingHint: "AI 正在分析简历并逐题誊写，请稍候，约需 10-30 秒。",
    printingRowPrefix: "题",
    printingRowWriting: "誊写中",
    printingBinding: "装订成卷……",
    noResume: "请先选择一份简历档案。",
    noPosition: "请填写目标岗位。",
    createFailed: "出题没有完成：考官暂时无法落笔，请稍后重试。",
    unauthorized: "未登录，请回登录页重新登记。",
  },
  interview: {
    title: "面试现场 · 面镜 Mirror",
    headerLabel: "现场作答 · 考官评分簿",
    abandonButton: "放弃面试",
    abandonConfirm: "确认缺考离场？本场面试将盖上「缺考」章，无法继续作答。",
    abandonFailed: "弃考没有完成，请重试一次。",
    answerLabel: "作答区",
    answerPlaceholder: "在此作答……（Enter 发送，Shift+Enter 换行）",
    sendButton: "提交作答",
    examinerLabel: "考官",
    candidateLabel: "候选人",
    followupTag: "追问",
    stampLabel: "批改",
    stampStarLabel: "STAR 完整度",
    progressTitle: "答题卡",
    questionLabelPrefix: "第",
    skillTagLabel: "考察点",
    gradingDoneTitle: "阅卷完成",
    gradingDoneHint: "本场作答已全部收录评分簿，正在合卷生成报告。",
    viewReport: "查看报告",
    abandonedStamp: "缺考",
    abandonedHint: "本场面试已盖「缺考」章，卷面封存，无法继续作答。",
    notFound: "这场面试不存在，或不在你的名下。",
    notInProgress: "这场面试不在进行中。",
    startFailed: "考官未能开场，请刷新本页重试。",
    answerFailed: "作答没有送达，请重试一次。",
    streamBroken: "流式中断：考官的话没有记全，刷新本页可恢复已落盘的卷面。",
    streamInterrupted: "……（话术中断）",
    llmFailed: "考官暂时无法落笔，请稍后重试。",
    unauthorized: "未登录，请回登录页重新进场。",
    loadFailed: "卷面没有取回，请刷新本页。",
    dimensions: {
      relevance: "相关性",
      depth: "深度",
      structure: "结构化",
      communication: "沟通",
    },
  },
  report: {
    title: "评分报告 · 面镜 Mirror",
    headerLabel: "阅卷完成 · 评语册",
    loadFailed: "评语册没有取回，请刷新本页。",
    notCompleted: "这场面试尚未阅卷完成，还出不了评语册。",
    emptyTitle: "评语册待誊写",
    emptyHint: "本场作答已合卷归档，教练尚未落笔。点击下方按钮，誊写本场的评分报告。",
    generateButton: "誊写评分报告",
    generating: "教练正在誊写评语册……",
    generateFailed: "报告没有誊成，请重试一次。",
    unauthorized: "未登录，请回登录页重新查看。",
    overallLabel: "总分",
    fullMarkLabel: "/ 100",
    radarTitle: "四维雷达",
    radarHint: "每维先看与目标的差距，再看分值。",
    gapPrefix: "距目标",
    gapUnit: "分",
    gapClose: "已贴目标线",
    gapNear: "方向已对，再补细节",
    gapMid: "要点有缺，回卷补齐",
    gapFar: "差距尚大，须从头重练",
    scoresLabel: "四维分",
    perQuestionTitle: "逐题批注",
    perQuestionHint: "亮点为黑墨誊录，不足为红笔批注，每条不足都附具体改法。",
    questionLabelPrefix: "第",
    questionLabelSuffix: "题",
    strengthsLabel: "亮点",
    improvementsLabel: "不足",
    coachTitle: "教练评语",
    coachSummaryLabel: "总结",
    coachStrengthsLabel: "优势",
    coachImprovementsLabel: "改进",
  },
  api: {
    unauthorized: "未登录",
  },
} as const;
