export const COPY = {
  login: {
    title: "登录 · 面镜 Mirror",
    brand: "面镜 Mirror",
    tagline: "照镜子式演练：面试是自我认知的镜子。",
    coverLabel: "考官评分簿 · 第 001 册",
    coverUsageLabel: "演练",
    coverUsageValue: "结构陪练 · 考官追问",
    coverScoringLabel: "批改",
    coverScoringValue: "四维评分 · 逐题批注",
    formTitle: "登录",
    formHint: "邮箱登录，无需密码。",
    emailLabel: "邮箱",
    emailPlaceholder: "输入邮箱",
    magicLink: "发送登录链接",
    github: "使用 GitHub 登录",
    sent: "登录链接已发送，请查收邮箱。",
    emailError: "这行字有问题，换一个邮箱试试。",
    authError: "登录没有完成，请回卷重试。",
  },
  resumes: {
    title: "简历 · 面镜 Mirror",
    headerLabel: "卷宗索引 · 简历档案库",
    headerTitle: "简历档案库",
    headerHint: "一卷一卡：每份简历是一张实体档案卡，供各场面试调阅。",
    newArchiveEyebrow: "考官誊录处",
    newArchiveTitle: "新建档案",
    newArchiveHint: "上传 PDF 由考官誊录，或直接粘贴文本入卷。",
    uploadLabel: "上传 PDF 文件",
    uploadHint: "仅收 PDF 原件；扫描件无法誊录。",
    uploadButton: "誊录入卷",
    uploading: "誊录中…",
    pasteLabel: "粘贴简历文本",
    pasteHint: "手边没有 PDF？粘贴全文，效力等同原件入卷。",
    pastePlaceholder: "在此粘贴简历全文……",
    pasteButton: "存为档案",
    saving: "入卷中…",
    listTitle: "档案索引",
    listHint: "按归档时间排序，新档在后。",
    listEmptyTitle: "尚未建档",
    listEmptyHint: "上传第一份简历，面试开卷有据。",
    archiveNoPrefix: "档案",
    dateLabel: "归档日期",
    profileLabel: "画像摘要",
    profileExpand: "展开画像",
    profileCollapse: "收起画像",
    profilePending: "画像待生成：此档案将在首场面试时完成结构化。",
    deleteButton: "销档",
    deleting: "销档中…",
    deleteConfirm: "确认销档？此档案的面试记录将一并销毁。",
    successNote: "已入卷。",
    pasteTooShort: "文本太短：不足 50 字，请粘贴完整简历。",
    notPdf: "仅收 PDF 原件：这份文件不是 PDF，换一份试试。",
    scanned: "誊录失败：这份 PDF 的文本太少，可能是扫描件，请用文字版 PDF。",
    uploadFailed: "誊录没有完成，请重试一次。",
    pasteFailed: "没有存进去，请重试一次。",
    deleteFailed: "销档没有完成，请重试一次。",
    loadFailed: "档案索引没有取回，请刷新本页。",
    loading: "取卷中…",
  },
  api: {
    unauthorized: "未登录",
  },
} as const;
